openapi: 3.0.3
info:
  title: Task Management API
  version: 1.0.0
  description: |
    RESTful API для системы управления задачами.
    Уровень зрелости Richardson: Level 3 (HATEOAS)
  contact:
    name: API Support
    email: support@taskmanager.example.com

servers:
  - url: https://api.taskmanager.example.com/api/v1
    description: Production
  - url: http://localhost:8080/api/v1
    description: Local development

tags:
  - name: Tasks
    description: Операции с задачами
  - name: Comments
    description: Комментарии к задачам

paths:
  /tasks:
    get:
      summary: Получить список задач с фильтрацией, сортировкой и пагинацией
      operationId: getTasks
      tags:
        - Tasks
      parameters:
        - name: status
          in: query
          schema:
            type: string
            enum: [TODO, IN_PROGRESS, DONE]
        - name: assignee
          in: query
          schema:
            type: string
        - name: priority
          in: query
          schema:
            type: string
            enum: [LOW, MEDIUM, HIGH, CRITICAL]
        - name: sort
          in: query
          description: "Пример: priority:desc,createdAt:asc"
          schema:
            type: string
            pattern: ^[a-zA-Z]+:(asc|desc)(,[a-zA-Z]+:(asc|desc))*$
        - $ref: '#/components/parameters/PageParam'
        - $ref: '#/components/parameters/SizeParam'
      responses:
        '200':
          description: Пагинированный список задач
          content:
            application/hal+json:
              schema:
                $ref: '#/components/schemas/TaskListResponse'

    post:
      summary: Создать новую задачу
      operationId: createTask
      tags:
        - Tasks
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateTaskRequest'
      responses:
        '201':
          description: Задача создана
          headers:
            Location:
              schema:
                type: string
                format: uri
          content:
            application/hal+json:
              schema:
                $ref: '#/components/schemas/Task'

  /tasks/{taskId}:
    parameters:
      - $ref: '#/components/parameters/TaskIdParam'

    get:
      summary: Получить задачу по ID
      operationId: getTaskById
      tags:
        - Tasks
      responses:
        '200':
          description: Задача найдена
          content:
            application/hal+json:
              schema:
                $ref: '#/components/schemas/Task'
        '404':
          $ref: '#/components/responses/NotFound'

    put:
      summary: Полная замена задачи
      operationId: updateTask
      tags:
        - Tasks
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateTaskRequest'
      responses:
        '200':
          description: Задача обновлена
          content:
            application/hal+json:
              schema:
                $ref: '#/components/schemas/Task'

    patch:
      summary: Частичное обновление задачи
      operationId: patchTask
      tags:
        - Tasks
      requestBody:
        required: true
        content:
          application/merge-patch+json:
            schema:
              $ref: '#/components/schemas/MergePatchTaskRequest'
          application/json-patch+json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/JsonPatchOperation'
      responses:
        '200':
          description: Задача обновлена
          content:
            application/hal+json:
              schema:
                $ref: '#/components/schemas/Task'

    delete:
      summary: Удалить задачу
      operationId: deleteTask
      tags:
        - Tasks
      responses:
        '204':
          description: Задача удалена

  /tasks/{taskId}/comments:
    parameters:
      - $ref: '#/components/parameters/TaskIdParam'
    get:
      summary: Получить комментарии к задаче
      operationId: getTaskComments
      tags:
        - Comments
      responses:
        '200':
          description: Список комментариев
          content:
            application/hal+json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Comment'

components:
  parameters:
    TaskIdParam:
      name: taskId
      in: path
      required: true
      description: UUID задачи
      schema:
        type: string
        format: uuid
        example: 3fa85f64-5717-4562-b3fc-2c963f66afa6

    PageParam:
      name: page
      in: query
      description: Номер страницы (с 0)
      schema:
        type: integer
        minimum: 0
        default: 0

    SizeParam:
      name: size
      in: query
      description: Размер страницы
      schema:
        type: integer
        minimum: 1
        maximum: 100
        default: 20

  responses:
    NotFound:
      description: Ресурс не найден
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'

  schemas:
    Link:
      type: object
      required:
        - href
      properties:
        href:
          type: string
          format: uri
        templated:
          type: boolean
          default: false

    ErrorResponse:
      type: object
      required:
        - timestamp
        - status
        - error
        - message
        - path
      properties:
        timestamp:
          type: string
          format: date-time
        status:
          type: integer
        error:
          type: string
        message:
          type: string
        path:
          type: string

    Task:
      type: object
      required:
        - id
        - title
        - status
        - priority
        - createdAt
      properties:
        id:
          type: string
          format: uuid
          readOnly: true
        title:
          type: string
          minLength: 3
          maxLength: 200
        description:
          type: string
          nullable: true
          maxLength: 5000
        status:
          type: string
          enum: [TODO, IN_PROGRESS, DONE]
          default: TODO
        priority:
          type: string
          enum: [LOW, MEDIUM, HIGH, CRITICAL]
          default: MEDIUM
        assignee:
          type: string
          nullable: true
        dueDate:
          type: string
          format: date-time
          nullable: true
        tags:
          type: array
          items:
            type: string
        createdAt:
          type: string
          format: date-time
          readOnly: true
        updatedAt:
          type: string
          format: date-time
          readOnly: true
        _links:
          type: object
          properties:
            self:
              $ref: '#/components/schemas/Link'
            comments:
              $ref: '#/components/schemas/Link'
            assignee:
              $ref: '#/components/schemas/Link'
            update:
              $ref: '#/components/schemas/Link'
            delete:
              $ref: '#/components/schemas/Link'

    CreateTaskRequest:
      type: object
      required:
        - title
      properties:
        title:
          type: string
          minLength: 3
          maxLength: 200
        description:
          type: string
          maxLength: 5000
        priority:
          type: string
          enum: [LOW, MEDIUM, HIGH, CRITICAL]
          default: MEDIUM
        assignee:
          type: string
          nullable: true
        dueDate:
          type: string
          format: date-time
          nullable: true
        tags:
          type: array
          items:
            type: string

    UpdateTaskRequest:
      allOf:
        - $ref: '#/components/schemas/CreateTaskRequest'
        - type: object
          properties:
            status:
              type: string
              enum: [TODO, IN_PROGRESS, DONE]

    MergePatchTaskRequest:
      type: object
      properties:
        title:
          type: string
          nullable: true
        description:
          type: string
          nullable: true
        status:
          type: string
          enum: [TODO, IN_PROGRESS, DONE]
          nullable: true
        priority:
          type: string
          enum: [LOW, MEDIUM, HIGH, CRITICAL]
          nullable: true
        assignee:
          type: string
          nullable: true
        dueDate:
          type: string
          format: date-time
          nullable: true
        tags:
          type: array
          nullable: true
          items:
            type: string

    JsonPatchOperation:
      type: object
      required:
        - op
        - path
      properties:
        op:
          type: string
          enum: [add, remove, replace, move, copy, test]
        path:
          type: string
        from:
          type: string
        value: {}

    TaskListResponse:
      type: object
      properties:
        _embedded:
          type: object
          properties:
            tasks:
              type: array
              items:
                $ref: '#/components/schemas/Task'
        page:
          type: object
          properties:
            size:
              type: integer
            totalElements:
              type: integer
              format: int64
            totalPages:
              type: integer
            number:
              type: integer
        _links:
          type: object
          properties:
            self:
              $ref: '#/components/schemas/Link'
            first:
              $ref: '#/components/schemas/Link'
            prev:
              $ref: '#/components/schemas/Link'
            next:
              $ref: '#/components/schemas/Link'
            last:
              $ref: '#/components/schemas/Link'

    Comment:
      type: object
      required:
        - id
        - text
        - author
        - createdAt
      properties:
        id:
          type: string
          format: uuid
        text:
          type: string
          minLength: 1
        author:
          type: string
        createdAt:
          type: string
          format: date-time
        _links:
          type: object
          properties:
            self:
              $ref: '#/components/schemas/Link'